# This is a basic workflow to help you get started with Actions

name: WDIO-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Where to get process.parameters that have set in the .env for local runs (.env will not be in repo as would usually contain secret details)
    env:  
      RUNNER: ${{secrets.RUNNER}}
      LOG_LEVEL_WINSTON: ${{secrets.LOG_LEVEL_WINSTON}}
      NOP_COMMERCIAL_ADMIN_EMAIL: = ${{secrets.NOP_COMMERCIAL_ADMIN_EMAIL}}
      NOP_COMMERCIAL_ADMIN_PASSWORD: = ${{secrets.NOP_COMMERCIAL_ADMIN_PASSWORD}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:


      # Install Chromium - required for any linux based server to run Chrome
      - name: Install Chromium
        run: sudo apt-get install chromium-browser
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Running smoke tests
        run: npm run demo:e2eUsers:silent:headless
      
